# This is a basic workflow to help you get started with Actions

name: generate-and-scp-config

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'    
      - run: |
          python3 driver.py

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy file to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ./config.json ubuntu@ec2-3-141-165-223.us-east-2.compute.amazonaws.com:/home/ubuntu/mockoonpoc
