# This is a basic workflow to help you get started with Actions

name: generate-and-scp-config

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Python Action
      uses: jge162/Action-workflows@v2.1.1

    - run: |
        echo "Install required dependencies" 
        sudo apt-get update
        sudo apt-get install python3
