# This is a basic workflow to help you get started with Actions

name: generate-and-scp-config

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - run: |
        with open(driver.py, 'r') as file:
          exec(file.read())
