# This is a basic workflow to help you get started with Actions

name: generate-and-scp-config

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'    
      - run: |
          python3 driver.py

      - name: SCP Config
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './config.json'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '/home/ubuntu/mockoonpoc'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.USERNAME}}                                      # Remote server user - REQUIRED true
          key: ${{secrets.SCP_SECRET_KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
          scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''
