# This is a basic workflow to help you get started with Actions

name: generate-and-scp-config

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'    
      - run: |
          python3 driver.py

      - name: SCP
        uses: moonpathbg/scp_uploader@latest
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key : ${{ secrets.SCP_SECRET_KEY }}
            source: "./config.json"
            target: "/home/ubuntu/mockoonpoc"
          
